AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the AWS::DevOpsGuru::NotificationChannel resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.devopsguru.notificationchannel.HandlerWrapper::handleRequest
      Runtime: java8
      MemorySize: 512
      CodeUri: ./target/aws-devopsguru-notificationchannel-1.0.jar

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.devopsguru.notificationchannel.HandlerWrapper::testEntrypoint
      Runtime: java8
      MemorySize: 512
      CodeUri: ./target/aws-devopsguru-notificationchannel-1.0.jar
